// RobotBuilder Version: 5.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

// ROBOTBUILDER TYPE: Subsystem.

package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.drive.KilloughDrive;
import edu.wpi.first.wpilibj.motorcontrol.MotorController;
import edu.wpi.first.wpilibj.motorcontrol.MotorControllerGroup;
import edu.wpi.first.wpilibj.motorcontrol.PWMVictorSPX;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class Drive extends SubsystemBase {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private PWMVictorSPX h_Wheels;
private PWMVictorSPX frontLeft;
private PWMVictorSPX backLeft;
private MotorControllerGroup left;
private PWMVictorSPX frontRight;
private PWMVictorSPX backRight;
private MotorControllerGroup right;
private KilloughDrive killoughDrive1;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    
    /**
    *
    */
    public Drive() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
h_Wheels = new PWMVictorSPX(0);
 addChild("H_Wheels",h_Wheels);
 h_Wheels.setInverted(false);

frontLeft = new PWMVictorSPX(1);
 addChild("frontLeft",frontLeft);
 frontLeft.setInverted(false);

backLeft = new PWMVictorSPX(2);
 addChild("backLeft",backLeft);
 backLeft.setInverted(true);

left = new MotorControllerGroup(frontLeft, backLeft  );
 addChild("Left",left);
 

frontRight = new PWMVictorSPX(3);
 addChild("frontRight",frontRight);
 frontRight.setInverted(false);

backRight = new PWMVictorSPX(4);
 addChild("backRight",backRight);
 backRight.setInverted(true);

right = new MotorControllerGroup(frontRight, backRight  );
 addChild("Right",right);
 

killoughDrive1 = new KilloughDrive(left, right,
h_Wheels);
 addChild("Killough Drive 1",killoughDrive1);
 killoughDrive1.setSafetyEnabled(true);
killoughDrive1.setExpiration(0.1);
killoughDrive1.setMaxOutput(1.0);



    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }

    @Override
    public void periodic() {
        // This method will be called once per scheduler run

    }

    @Override
    public void simulationPeriodic() {
        // This method will be called once per scheduler run when in simulation

    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}

